spring:
  application:
    name: school_hackathon_2025

  datasource:
    username: root
    password: 312819
    url: jdbc:mysql://localhost:3306/hack

  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
  graphql:
    cors:
      allowed-origins: https://hackerton-fe.vercel.app, http://localhost:3000
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH, HEAD, TRACE, CONNECT
      allowed-headers: Content-Type, Authorization, X-Requested-With, Accept, Origin, X-HTTP-Method-Override, Access-Control-Allow-Origin, Access-Control-Allow-Credentials, Access-Control-Allow-Headers, Access-Control-Allow-Methods, Access-Control-Expose-Headers, Access-Control-Max-Age, Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Access-Control-Allow-Methods, Access-Control-Expose-Headers, Access-Control-Max-Age
      allow-credentials: true
      max-age: 3600
server:
  servlet:
    context-path: /api

cors:
